# ==========================
# Frontend PROD
# ==========================
FROM nginx:stable-alpine

RUN rm -rf /usr/share/nginx/html/*

COPY mi-web/ /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
