apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-test
spec:
  containers:
  - name: test
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: db-secret-volume
      mountPath: /etc/secrets
      readOnly: true

  volumes:
  - name: db-secret-volume
    secret:
      secretName: db-secret