services:

  # ==========================
  # Nginx Reverse Proxy
  # ==========================
  nginx:
    build:
      context: ..
      dockerfile: nginx/Dockerfile.dev
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - web_net
      - backend_net
    restart: unless-stopped

  # ==========================
  # Backend API
  # ==========================
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - env/dev/.env
    depends_on:
      - postgres
    networks:
      - backend_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 10s
      timeout: 3s
      retries: 3

  # ==========================
  # PostgreSQL Database
  # ==========================
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    env_file:
      - env/dev/.env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - backend_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # ==========================
  # Prometheus
  # ==========================
  prometheus:
    image: prom/prometheus:v3.3.0
    container_name: wellness-prometheus
    volumes:
      - ../monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - backend
    networks:
      - backend_net

  # ==========================
  # Grafana
  # ==========================
  grafana:
    image: grafana/grafana:11.6.1
    container_name: wellness-grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - backend_net

# ==========================
# Networks
# ==========================
networks:
  web_net:
    driver: bridge
  backend_net:
    driver: bridge

# ==========================
# Volumes
# ==========================
volumes:
  db-data: