# ==========================
# Nginx PROD - Reverse Proxy
# ==========================

FROM nginx:stable-alpine

# Remove default config
RUN rm /etc/nginx/conf.d/default.conf

# Copy production config
COPY nginx.prod.conf /etc/nginx/conf.d/default.conf
COPY certs /etc/nginx/certs

# Expose ports 80 and 443
EXPOSE 80 443
