FROM nginx:stable-alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY docker/nginx/nginx.dev.conf /etc/nginx/conf.d/default.conf
COPY frontend/mi-web/ /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
