FROM nginx:stable-alpine

# Eliminamos la config por defecto
RUN rm /etc/nginx/conf.d/default.conf

# Copiamos nuestra config de reverse proxy
COPY nginx.dev.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
