# ==========================
# Nginx PROD - Reverse Proxy
# ==========================

FROM nginx:stable-alpine

# Eliminamos config por defecto
RUN rm /etc/nginx/conf.d/default.conf

# Copiamos nuestra config de producción
COPY nginx.prod.conf /etc/nginx/conf.d/default.conf
COPY certs /etc/nginx/certs

# Exponemos puerto 80 (443 vendrá después)
EXPOSE 80 443
