name: CD PROD (tag → promote) 

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  promote:
    runs-on: self-hosted

    environment:
      name: production   # 👈 approval gate

    steps:
      # =========================
      # GET IMAGE FROM DEV
      # =========================
      - name: Get backend image from DEV
        run: |
          kubectl get deployment backend -n dev -o jsonpath='{.spec.template.spec.containers[0].image}' > backend_image.txt

      - name: Get frontend image from DEV
        run: |
          kubectl get deployment frontend -n dev -o jsonpath='{.spec.template.spec.containers[0].image}' > frontend_image.txt

      - name: Show images (debug)
        run: |
          echo "Backend: $(cat backend_image.txt)"
          echo "Frontend: $(cat frontend_image.txt)"

      # =========================
      # CHECKOUT GITOPS
      # =========================
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: luisrodvilladaorg/wellness-gitops
          token: ${{ secrets.GITOPS_TOKEN }}
          path: wellness-gitops

      # =========================
      # UPDATE PROD BACKEND
      # =========================
      - name: Update PROD backend image
        run: |
          BACKEND_IMAGE=$(cat backend_image.txt)
          sed -i "s|image: .*|image: $BACKEND_IMAGE|" \
          wellness-gitops/k8s/overlays/prod/backend/patch-image.yml

      # =========================
      # UPDATE PROD FRONTEND
      # =========================
      - name: Update PROD frontend image
        run: |
          FRONTEND_IMAGE=$(cat frontend_image.txt)
          sed -i "s|image: .*|image: $FRONTEND_IMAGE|" \
          wellness-gitops/k8s/overlays/prod/frontend/patch-image.yml

      # =========================
      # COMMIT GITOPS
      # =========================
      - name: Commit & push changes
        run: |
          cd wellness-gitops
          git config user.name "github-actions"
          git config user.email "ci@github.com"
          git add .
          git diff --quiet || git commit -m "prod: promote ${GITHUB_REF_NAME}"
          git push