name: Promote DEV → PROD (approval)

on:
  workflow_dispatch:

jobs:
  promote:
    runs-on: self-hosted

    environment:
      name: prod   # 👈 aquí está el approval gate

    steps:
      - name: Get current DEV backend image
        run: |
          kubectl get deployment backend -n dev -o jsonpath='{.spec.template.spec.containers[0].image}' > backend_image.txt

      - name: Get current DEV frontend image
        run: |
          kubectl get deployment frontend -n dev -o jsonpath='{.spec.template.spec.containers[0].image}' > frontend_image.txt

      - name: Show images
        run: |
          echo "Backend: $(cat backend_image.txt)"
          echo "Frontend: $(cat frontend_image.txt)"

      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: luisrodvilladaorg/wellness-gitops
          token: ${{ secrets.GITOPS_TOKEN }}
          path: wellness-gitops

      - name: Update backend PROD
        run: |
          BACKEND_IMAGE=$(cat backend_image.txt)
          sed -i "s|image: .*|image: $BACKEND_IMAGE|" \
          wellness-gitops/k8s/overlays/prod/backend/patch-image.yml

      - name: Update frontend PROD
        run: |
          FRONTEND_IMAGE=$(cat frontend_image.txt)
          sed -i "s|image: .*|image: $FRONTEND_IMAGE|" \
          wellness-gitops/k8s/overlays/prod/frontend/patch-image.yml

      - name: Commit & push
        run: |
          cd wellness-gitops
          git config user.name "github-actions"
          git config user.email "ci@github.com"
          git add .
          git commit -m "promote: approved to prod" || echo "No changes"
          git push